# Generated by Django 4.2.11 on 2024-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HostelDataClass",
            fields=[
                ("rollnumber", models.CharField(max_length=255)),
                ("studentname", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("hoastelalloted", models.CharField(max_length=255)),
                ("roomno", models.IntegerField(primary_key=True, serialize=False)),
                ("floorno", models.IntegerField()),
            ],
            options={"db_table": "hosteldata",},
        ),
        migrations.CreateModel(
            name="HostelReviews",
            fields=[
                (
                    "rollnumber",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("studentname", models.CharField(max_length=255)),
                ("hostelnum", models.CharField(max_length=255)),
                ("review", models.CharField(max_length=1000)),
            ],
            options={"db_table": "hostelreviews",},
        ),
    ]
